### ISSUE TITLE
TypeError: unorderable types: bytes() < str()

### ISSUE THREAD

**Issue by greatken999** [tensorflow/minigo#122]
run : python3 local_rl_loop.py ,get error info:

Traceback (most recent call last):
  File "local_rl_loop.py", line 109, in <module>
    rl_loop()
  File "local_rl_loop.py", line 99, in rl_loop
    main.gather(input_directory=selfplay_dir, output_directory=gather_dir)
  File "/xxx/minigo/main.py", line 311, in gather
    f.write('\n'.join(sorted(already_processed)))
TypeError: unorderable types: bytes() < str()

**Comment by amj** [comment]
Do you have unicode in your filenames?

**Comment by greatken999** [comment]
it's fine last code
