### ISSUE TITLE
AlreadyExistsError: file already exists

### ISSUE THREAD

**Issue by greatken999** [tensorflow/minigo#125]
Traceback (most recent call last):
  File "local_rl_loop.py", line 122, in <module>
    rl_loop()
  File "local_rl_loop.py", line 108, in rl_loop
    main.train(working_dir, gather_dir, next_model_save_file, generation_num=1)
  File "/xxx/minigo/main.py", line 110, in train
    dual_net.export_model(working_dir, model_save_path)
  File "xxx/minigo/dual_net.py", line 450, in export_model
    tf.gfile.Copy(filename, destination_path)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/lib/io/file_io.py", line 385, in copy
    compat.as_bytes(oldpath), compat.as_bytes(newpath), overwrite, status)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.AlreadyExistsError: file already exists

**Comment by amj** [comment]
This is super strange; are you using the temporary directory still?  what OS is this?

**Comment by greatken999** [comment]
it's look fine last code
