### ISSUE TITLE
AttributeError: module 'gtp' has no attribute 'Engine'

### ISSUE THREAD

**Issue by david2588e** [tensorflow/minigo#145]
C:\Users\Liu\Anaconda2\envs\py3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    from gtp_wrapper import make_gtp_instance, MCTSPlayer
  File "D:\Training\机器读心术之神经网络与深度学习（第九期）\第10课\minigo-master(2)\minigo-master\gtp_wrapper.py", line 16, in <module>
    import gtp_extensions
  File "D:\Training\机器读心术之神经网络与深度学习（第九期）\第10课\minigo-master(2)\minigo-master\gtp_extensions.py", line 42, in <module>
    class KgsExtensionsMixin(gtp.Engine):
AttributeError: module 'gtp' has no attribute 'Engine'

**Comment by amj** [comment]
we no longer have the gtp dependency, so this should be, if not fixed, at least a different bug :)  Closing.

**Comment by chenwenyan** [comment]
i have the same error when running the MLPerf training workloads.
the output is 

Traceback (most recent call last):
  File "loop_init.py", line 21, in <module>
    import main
  File "/data/training/reinforcement/tensorflow/minigo/main.py", line 35, in <module>
    from gtp_wrapper import make_gtp_instance, MCTSPlayer
  File "/data/training/reinforcement/tensorflow/minigo/gtp_wrapper.py", line 16, in <module>
    import gtp_extensions
  File "/data/training/reinforcement/tensorflow/minigo/gtp_extensions.py", line 42, in <module>
    class KgsExtensionsMixin(gtp.Engine):
AttributeError: module 'gtp' has no attribute 'Engine'


and the ptp version=0.2
