### ISSUE TITLE
Ringmaster gets stuck after "Passing wins :)"

### ISSUE THREAD

**Issue by sethtroisi** [tensorflow/minigo#431]
passing wins seems to come from leela-zero. I'm not sure what minigo is doing at this point.

```
def minigo_player(readouts):
    return Player(
        "python3 gtp.py --load_file saved_models/000303-olympus --conv_width=128 --trunk_layers=19 --c_puct=1 --use_random_symmetry=True --verbose=5 --parallel_readouts=1 --num_readouts=" +             str(readouts),
        cwd="~/Projects/minigo/",
        environ={'BOARD_SIZE' : '19'})
```

LOG
```
Passing wins :-)
run interrupted at 2018-09-11 02:06
games in progress were: 0_14
Traceback (most recent call last):
  File "gtp.py", line 90, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 274, in run
    _run_main(main, argv)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 238, in _run_main
    sys.exit(main(argv))
  File "gtp.py", line 85, in main
    if not engine.handle_msg(msg.strip()):
  File "/home/eights/Projects/minigo/gtp_engine.py", line 167, in handle_msg
    _print_success(msg_id, handler(*args))
  File "/home/eights/Projects/minigo/gtp_cmd_handlers.py", line 84, in cmd_genmove
    move = self._player.suggest_move(self._player.get_position())
  File "/home/eights/Projects/minigo/strategies.py", line 142, in suggest_move
    self.tree_search()
  File "/home/eights/Projects/minigo/strategies.py", line 203, in tree_search
    leaf = self.root.select_leaf()
  File "/home/eights/Projects/minigo/mcts.py", line 150, in select_leaf
    node.child_N[pass_move] == 0):
KeyboardInterrupt
```

**Comment by sethtroisi** [comment]
This happened again. At readout 139 of 200 it just stalls.
htop shows 100% CPU usage, nvidia-smi shows 0% GPU usage same stack trace.

**Comment by sethtroisi** [comment]
found the root problem was a typo, embarrassing.
