### ISSUE TITLE
what's the problem?

### ISSUE THREAD

**Issue by fmscole** [tensorflow/minigo#548]
```
FLAGS.num_readouts: 800
Q: -0.53095
9: 800 readouts, 0.082 s/100. (0.66 sec)
D:\projects\minigo13\strategies.py:183: RuntimeWarning: divide by zero encountered in true_divide
  cdf /= cdf[-2]  # Prevents passing via softpick.
D:\projects\minigo13\strategies.py:183: RuntimeWarning: invalid value encountered in true_divide
  cdf /= cdf[-2]  # Prevents passing via softpick.
Traceback (most recent call last):
  File "my_train.py", line 22, in <module>
    selfplay.main(None)
  File "D:\projects\minigo13\selfplay.py", line 162, in main
    verbose=FLAGS.verbose)
  File "D:\projects\minigo13\selfplay.py", line 124, in run_game
    player = play(network, verbose)
  File "D:\projects\minigo13\selfplay.py", line 88, in play
    move = player.pick_move()
  File "D:\projects\minigo13\strategies.py", line 186, in pick_move
    assert self.root.child_N[fcoord] != 0
AssertionError
```

**Comment by amj** [comment]
it's trying to pick a move with no visits.  how are you running this?

**Comment by amj** [comment]
closed as no further details added after 30d
