### ISSUE TITLE
Is there any trained network other than v199-lightning available for download?

### ISSUE THREAD

**Issue by wpstmxhs** [tensorflow/minigo#568]
Hi.

I'm interested in minigo project.
I found the website which reports the current status of minigo project,
( https://cloudygo.com/ )
but I couldn't find how to download the newest network file.

Can I download trained networks other than v199-lightning?

Thanks.

**Comment by sethtroisi** [comment]
Absolutely. 

Lots of our older models are made public in minigo-pub
https://console.cloud.google.com/storage/browser/minigo-pub/v12-19x19/models

I don't think that v13 is there yet but I'll add it in  ~5 minutes

**Comment by wpstmxhs** [comment]
@sethtroisi 

Wow, I'm very excited to test it!
Thank you for your lightning-fast answer!

**Comment by wpstmxhs** [comment]
@sethtroisi 

Did you solve your problem with TensorFlow model importing?

I have the same problem that you had:

```
saver = tf.train.import_meta_graph('000708-icarus.meta')
```

```
Traceback (most recent call last):
  File "convert.py", line 11, in <module>
    saver = tf.train.import_meta_graph(sys.argv[1]+'.meta')
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 1674, in import_meta_graph
    meta_graph_or_file, clear_devices, import_scope, **kwargs)[0]
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 1696, in _import_meta_graph_with_return_elements
    **kwargs))
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\meta_graph.py", line 806, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\importer.py", line 391, in import_graph_def
    _RemoveDefaultAttrs(op_dict, producer_op_list, graph_def)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\importer.py", line 158, in _RemoveDefaultAttrs
    op_def = op_dict[node.op]
KeyError: 'InfeedEnqueueTuple'
```

**Comment by amj** [comment]
@wpstmxhs if you're trying to run the weights in the minigo cc engine, i recommend downloading the .pb files -- they're a single-file with all the weights needed.

**Comment by amj** [comment]
@wpstmxhs does this work for you?  If so, please close this issue :)
