### ISSUE TITLE
Assign requires shapes of both tensors to match. lhs shape= [1,1,256,2] rhs shape= [3,3,256,256]

### ISSUE THREAD

**Issue by chunmwan** [tensorflow/minigo#696]
(tensorflow) C:\Users\chunmwan\Downloads\minigo>python gtp.py --load_file=models\000798-golden-lion --num_readouts=400 --verbose=3

when I used v16 798 weights and runned gtp.py, go below error:
  File "C:\Users\chunmwan\Downloads\minigo\dual_net.py", line 165, in initialize_weights
    tf.train.Saver().restore(self.sess, save_file)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 1574, in restore
    err, "a mismatch between the current graph and the graph")
tensorflow.python.framework.errors_impl.InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [1,1,256,2] rhs shape= [3,3,256,256]
         [[{{node save/Assign_305}} = Assign[T=DT_FLOAT, _class=["loc:@conv2d_39/kernel"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](conv2d_39/kernel/Momentum, save/RestoreV2:305)]]

**Comment by brilee** [comment]
Try using the flag `--trunk_layers 39` or maybe `--trunk_layers 40`. The checkpoint itself has no metadata indicating the depth of the network being used.

**Comment by chunmwan** [comment]
(tensorflow) C:\Users\chunmwan\Downloads\minigo>python selfplay.py --load_file=models\000798-golden-lion --num_readouts 10 --verbose 3 --selfplay_dir=outputs\data\selfplay --holdout_dir=outputs\data\holdout --sgf_dir=outputs\sgf --trunk_layers 40
2019-02-09 20:56:39.808252: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
I0209 20:56:39.818232 25008 dual_net.py:146] TPU inference is supported on C++ only. DualNetwork will ignore use_tpu=True
I0209 20:56:49.060407 25008 tf_logging.py:115] Restoring parameters from models\000798-golden-lion
2019-02-09 20:56:49.453513: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key batch_normalization_79/beta not found in checkpoint
Traceback (most recent call last):
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1292, in _do_call
    return fn(*args)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1277, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1367, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key batch_normalization_79/beta not found in checkpoint
         [[{{node save/RestoreV2}} = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 1538, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 887, in run
    run_metadata_ptr)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1286, in _do_run
    run_metadata)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key batch_normalization_79/beta not found in checkpoint
         [[{{node save/RestoreV2}} = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op 'save/RestoreV2', defined at:
  File "selfplay.py", line 163, in <module>
    app.run(main)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "selfplay.py", line 159, in main
    sgf_dir=FLAGS.sgf_dir)
  File "selfplay.py", line 122, in run_game
    network = dual_net.DualNetwork(load_file)
  File "C:\Users\chunmwan\Downloads\minigo\dual_net.py", line 140, in __init__
    self.initialize_graph()
  File "C:\Users\chunmwan\Downloads\minigo\dual_net.py", line 155, in initialize_graph
    self.initialize_weights(self.save_file)
  File "C:\Users\chunmwan\Downloads\minigo\dual_net.py", line 165, in initialize_weights
    tf.train.Saver().restore(self.sess, save_file)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 1094, in __init__
    self.build()
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 1106, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 1143, in _build
    build_save=build_save, build_restore=build_restore)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 787, in _build_internal
    restore_sequentially, reshape)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 406, in _AddRestoreOps
    restore_sequentially)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 854, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1549, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 3272, in create_op
    op_def=op_def)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Key batch_normalization_79/beta not found in checkpoint
         [[{{node save/RestoreV2}} = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 1548, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 1822, in object_graph_key_mapping
    checkpointable.OBJECT_GRAPH_PROTO_KEY)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 359, in get_tensor
    status)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 526, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "selfplay.py", line 163, in <module>
    app.run(main)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "selfplay.py", line 159, in main
    sgf_dir=FLAGS.sgf_dir)
  File "selfplay.py", line 122, in run_game
    network = dual_net.DualNetwork(load_file)
  File "C:\Users\chunmwan\Downloads\minigo\dual_net.py", line 140, in __init__
    self.initialize_graph()
  File "C:\Users\chunmwan\Downloads\minigo\dual_net.py", line 155, in initialize_graph
    self.initialize_weights(self.save_file)
  File "C:\Users\chunmwan\Downloads\minigo\dual_net.py", line 165, in initialize_weights
    tf.train.Saver().restore(self.sess, save_file)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 1554, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key batch_normalization_79/beta not found in checkpoint
         [[{{node save/RestoreV2}} = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op 'save/RestoreV2', defined at:
  File "selfplay.py", line 163, in <module>
    app.run(main)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "selfplay.py", line 159, in main
    sgf_dir=FLAGS.sgf_dir)
  File "selfplay.py", line 122, in run_game
    network = dual_net.DualNetwork(load_file)
  File "C:\Users\chunmwan\Downloads\minigo\dual_net.py", line 140, in __init__
    self.initialize_graph()
  File "C:\Users\chunmwan\Downloads\minigo\dual_net.py", line 155, in initialize_graph
    self.initialize_weights(self.save_file)
  File "C:\Users\chunmwan\Downloads\minigo\dual_net.py", line 165, in initialize_weights
    tf.train.Saver().restore(self.sess, save_file)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 1094, in __init__
    self.build()
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 1106, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 1143, in _build
    build_save=build_save, build_restore=build_restore)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 787, in _build_internal
    restore_sequentially, reshape)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 406, in _AddRestoreOps
    restore_sequentially)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 854, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1549, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 3272, in create_op
    op_def=op_def)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key batch_normalization_79/beta not found in checkpoint
         [[{{node save/RestoreV2}} = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

**Comment by brilee** [comment]
What a stack trace! I think it's saying you should use `--trunk_layers 39`.

**Comment by amj** [comment]
ah yeah @brilee is right.  We use 19 or 39; we used 20 only for the v12 models i think.

If you use the .pb's in the cc version, the graph structure is already defined so it doesn't matter.

**Comment by amj** [comment]
Closing as fixed, let us know if there are still issues.
