### ISSUE TITLE
minigo selfplay not support Cuda 10.0 ?

### ISSUE THREAD

**Issue by chunmwan** [tensorflow/minigo#834]
tried to run selfplay , but still got error:
(tensorflow) chunmwan@alphago:~/Downloads/minigo$ python selfplay.py --verbose=2 --num_readouts=400 --load_file=./models/000798-golden-lion
Traceback (most recent call last):
  File "/home/chunmwan/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/chunmwan/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/chunmwan/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/chunmwan/anaconda3/envs/tensorflow/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/chunmwan/anaconda3/envs/tensorflow/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

**Comment by tommadams** [comment]
What version of TensorFlow are you using?

```python3 -c 'import tensorflow as tf; print(tf.__version__)'```

You need to be running at least TF 1.13

**Comment by chunmwan** [comment]
after reinstall using conda install tensorflow, print version is 1.13, but after running :
(tensorflow) chunmwan@alphago:~/Downloads/minigo$ python3 selfplay.py --verbose=2 --num_readouts=400 --load_file ./models/000798-golden-lion
Use standard file APIs to check for files with this prefix.
I0503 07:39:00.873214 140372019242816 saver.py:1270] Restoring parameters from ./models/000798-golden-lion
Traceback (most recent call last):
  File "/home/chunmwan/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/chunmwan/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/chunmwan/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1,1,256,1] rhs shape= [3,3,256,256]
	 [[{{node save/Assign_308}}]]

**Comment by tommadams** [comment]
`000798-golden-lion` is a 40 block model, you will need to pass `--trunk_layers=39`

```
python3 selfplay.py --verbose=2 --num_readouts=400 --load_file ./models/000798-golden-lion --trunk_layers=39  --verbose=3
```
